version: '3'
services:
  mysql:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=mytestdb
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  web:
    image: 911191919191/spring-boot:1.0.0
    ports:
      - "8084:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mytestdb?&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "demo"
      dockerfile: "DockerFile"
    depends_on:
      - mysql
